# Generated by Django 5.1.2 on 2025-01-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsarticle_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sources', models.ManyToManyField(related_name='custom_feeds', to='news.newssource')),
            ],
        ),
    ]
